name: Test Github Actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: SSH To Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~
            mkdir -p app
            cd app
            git clone https://github.com/n3erajan/github-action-test.git
            cd github-action-test/
            docker compose up -d --build
